import { ambientCatalog } from '../ambient-catalog';
import V12LegalPage from '../components/V12LegalPage';

export const metadata = { title: 'Audio Licenses · Everlasting Voyage' };

const licensedRecordings = Object.values(ambientCatalog).filter((definition) =>
  Boolean(definition.assetPath && definition.sourcePage && definition.sourceCredit && definition.license)
);

function licenseLabel(license: 'public-domain' | 'cc0' | undefined): string {
  if (license === 'cc0') return 'CC0 / public-domain dedication';
  if (license === 'public-domain') return 'Public domain';
  return 'See source';
}

export default function AudioLicensesPage() {
  return (
    <V12LegalPage
      eyebrow="Audio licenses"
      title="The recordings behind Atmosphere."
      intro="This catalog lists the field recordings currently connected to the active Everlasting Voyage sound library. Procedural noise is generated by the application and does not use a recording."
    >
      <section>
        <h2>Active sourced recordings</h2>
        <div className="v12LicenseGrid">
          {licensedRecordings.map((definition) => (
            <article key={definition.id}>
              <span>{definition.shortName}</span>
              <h3>{definition.name}</h3>
              <dl>
                <div><dt>Original recording</dt><dd>{definition.sourceCredit}</dd></div>
                <div><dt>License</dt><dd>{licenseLabel(definition.license)}</dd></div>
                <div><dt>Use in Voyage</dt><dd>Encoded and level-balanced for seamless Atmosphere playback.</dd></div>
              </dl>
              <a href={definition.sourcePage} target="_blank" rel="noreferrer">View source attribution ↗</a>
            </article>
          ))}
        </div>
      </section>
      <section>
        <h2>Procedural textures</h2>
        <p>
          White Noise, Brown Noise and Pink Noise are synthesized in the browser from generated noise buffers. They do not contain a third-party field recording.
        </p>
      </section>
      <section>
        <h2>Questions about a recording</h2>
        <p>
          Use the Contact page and select an audio-licensing question. Retired or unavailable source files are not presented as active recordings on this page.
        </p>
      </section>
    </V12LegalPage>
  );
}
